name: vkget_flutter
description: VK SDK Flutter features
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  device_info: ^2.0.0
  flutter:
    sdk: flutter
  vkget: 
    path: ../vkget

dev_dependencies:
  pedantic: ^1.9.0
