name: vkget_flutter
description: VK SDK Flutter features
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  device_info_plus: ^3.2.1
  flutter:
    sdk: flutter
  vkget: 
    path: ../vkget

dev_dependencies:
  lints: ^1.0.1